; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32devota]
; platform = espressif32@6.7.0
; board = esp32dev
; framework = arduino
; lib_ldf_mode = deep+
; monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.1.243
; board_build.partitions  = min_spiffs.csv
; lib_deps = 
; 	lvgl/lvgl@^8.3.7
; 	bblanchon/ArduinoJson@^6.21.3
; 	knolleary/PubSubClient@^2.8
; #	-D LV_CONF_INCLUDE_SIMPLE

; build_flags = 
; 	-g
; 	-I .

; [env:esp32dev]
; platform = espressif32@6.7.0
; board = esp32dev
; framework = arduino
; lib_ldf_mode = deep+
; monitor_speed = 115200
; board_build.partitions  = min_spiffs.csv
; lib_deps = 
; 	lvgl/lvgl@^8.3.7
; 	bblanchon/ArduinoJson@^6.21.3
; 	knolleary/PubSubClient@^2.8
; #	-D LV_CONF_INCLUDE_SIMPLE

; build_flags = 
; 	-g
; 	-I .

; [env:esp32s3supermini]
; platform = espressif32@6.7.0
; board = esp32-s3-devkitc-1
; framework = arduino
; lib_ldf_mode = deep+
; monitor_speed = 115200
; upload_speed = 115200
; board_upload.flash_size = 4MB
; board_build.partitions = partitions_s3_4mb_ota.csv
; board_build.psram_type = qspi
; board_build.arduino.memory_type = qio_qspi
; lib_deps = 
; 	lvgl/lvgl@^8.3.7
; 	bblanchon/ArduinoJson@^6.21.3
; 	knolleary/PubSubClient@^2.8

; build_flags = 
; 	-g
; 	-I .
; 	-DBOARD_HAS_PSRAM
; 	-DUSE_HSPI_PORT

[env:esp32-s3-n4r2]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
upload_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
    lvgl/lvgl@^8.3.7
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

; --- N4R2 Configuration ---
board_build.mcu = esp32s3
board_build.flash_mode = qio
board_build.psram_type = qio
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = partitions_s3_4mb_ota.csv
build_flags = 
    -g
    -I .
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DUSE_HSPI_PORT
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ESP_COREDUMP_ENABLE=0
    -DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=0
